# Generated by Django 5.2.3 on 2025-07-01 15:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('original_image', models.ImageField(upload_to='originals/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='thumbnails/')),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('file_size', models.PositiveIntegerField()),
                ('format', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processing_progress', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EditingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brightness', models.IntegerField(default=0, help_text='-100 to 100')),
                ('contrast', models.IntegerField(default=0, help_text='-100 to 100')),
                ('saturation', models.IntegerField(default=0, help_text='-100 to 100')),
                ('vibrance', models.IntegerField(default=0, help_text='-100 to 100')),
                ('exposure', models.IntegerField(default=0, help_text='-100 to 100')),
                ('compression_quality', models.IntegerField(default=85, help_text='1 to 100')),
                ('output_format', models.CharField(default='JPEG', max_length=10)),
                ('background_color', models.CharField(default='#0066FF', max_length=7)),
                ('background_style', models.CharField(default='solid', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('photo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='editor.photo')),
            ],
        ),
        migrations.CreateModel(
            name='DetectedSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_type', models.CharField(choices=[('person', 'Person'), ('object', 'Object'), ('background', 'Background'), ('sky', 'Sky'), ('water', 'Water')], max_length=20)),
                ('mask_data', models.TextField()),
                ('confidence', models.FloatField()),
                ('bounding_box', models.JSONField()),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.photo')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='editor.project'),
        ),
    ]
